### ISSUE TITLE
Esi minimal configuration to work correctly

### ISSUE THREAD

**Issue by alexander-schranz** [alexander-schranz/sulu-form-bundle#128]
The following configuration is enough that the esi works correctly.

```yml
framework:
    esi: ~
    fragments: ~
```
