### ISSUE TITLE
Missing migrations

### ISSUE THREAD

**Issue by alexander-schranz** [alexander-schranz/sulu-form-bundle#143]
**Config:**

```
    `mail_helper` --> `mail`
```

**Dynamic List:**

Remove Services with class `L91\Sulu\Bundle\FormBundle\Provider\DynamicProvider` and the following tag:

```xml
<tag name="sulu_form.list_provider" template="form" />
```

use

```yml
sulu_form:
    dynamic_lists:
        content:
            <template_key>:
                property: <form_select_property_name>
```

**Mail Template**

If you have multiple template you need maybe do something like the following:

```twig
{% include app.request.attributes.get('structure').view ~ '-mail/form-notify.html.twig' %}
```

and:

```twig
{% include app.request.attributes.get('structure').view ~ '-mail/form-customer.html.twig' %}
```
